---
title: "p8105_hw2_jl5295"
author: "Jana Lee"
date: "9/29/2019"
output: github_document
---

# Problem 1: Mr. Trash Wheel
```{r}
library(tidyverse)
library(readxl)
  trashwheel = read_excel("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "Mr. Trash Wheel", range = cell_cols("A:N")) %>%
  janitor :: clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round (sports_balls))
```

```{r}
library(readxl)
precipitation_2017 = read_excel("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2017 Precipitation", range = cell_rows(2:14)) %>% 
  mutate(year = 2017)

precipitation_2018 = read_excel ("./Data/Trash-Wheel-Collection-Totals-8-6-19.xlsx", sheet = "2018 Precipitation", range = cell_rows(2:14)) %>% 
  mutate(year = 2018)

precipitation_final = bind_rows(precipitation_2017, precipitation_2018) %>% 
  mutate(Month = month.name[Month])
```



# Problem 2: FiveThirtyEight
```{r}
fivethirtyeight = read_csv(file = "./Data/fivethirtyeight_datasets/pols-month.csv")
```


# Problem 3: Popular Baby Names

## Loading and tidying the data
```{r}
library (dplyr)
babynames = read_csv(file = "./Data/Popular_Baby_Names.csv") %>%
  janitor :: clean_names() %>% 
  rename(birth_year = year_of_birth) %>% 
  distinct() %>% 
  mutate(ethnicity = replace (ethnicity, ethnicity == "ASIAN AND PACI", "ASIAN AND PACIFIC ISLANDER")) %>% 
  mutate(ethnicity = replace (ethnicity, ethnicity == "BLACK NON HISP", "BLACK NON HISPANIC")) %>% 
  mutate(ethnicity = replace (ethnicity, ethnicity == "WHITE NON HISP", "WHITE NON HISPANIC")) %>%
  mutate(childs_first_name = toupper(childs_first_name))
```
Description of what was done: 

## Creating a reader-friendly table for Olivia
```{r}

olivia = filter(babynames, childs_first_name == "OLIVIA") %>%
  select(-c("childs_first_name", "count", "gender"))  %>% 
  pivot_wider(
    names_from = "birth_year",
    values_from = "rank"
  )
```
## JANA CHECK ORDERING FOR YEARS.

## Scatterplot for male, white, non-hispanic children
```{r}

```

